[google_sheets]
type = "service_account"
project_id = "resolute-planet-457915"
private_key_id = "a85943f4d0bbed00803f7a50d5d222e39cc7d88a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCbm08qlFr0s9sW
vAbXyplWoCcpJxGt0/jLoQKbh+uejnHTX1BaoolSVi7ASfYrg4EqlSpCYKiLxHL0
GdfEBwVhkmy5d6m1+lAXJy2He4yJ0aM2/YdPifbFyeKrceDgg9Un+c6VUq4r/REM
HSJdx2pam6ASTi2m41t+FHb9/Jc7H5bzAfO5FsMJfbOJgTfy+F6iZFuxuySymyNk
Hi507YiWm7uSqbZH54cYGlwrRI06lvvlaM+LO137rsOJ5pxBWch6+LtD1TPI9XFh
T3R2slTcJgHMpQ6En4yT6yAG6XgYoHTW57O7qqGi6IkgA3d/VNu/ti5FoMiItY2N
zRCGP/SFAgMBAAECggEADEvLx/LUtCkBO0zs4oD3OH3r0kfs0PZi3t5wiQ9Gym75
pikOPbdB0DCQva+qhPo9ivqiDgA62V6S8eCX6PzgCzuJnWdMER4AVbAKHD5iVuKq
udXzaxDdH/iJ0Z/sU/l+7suB7FFOA5paDkHAHTZ8nD/XeJLWby1gpbgixgO/hJOl
DTd8bD67y5pOipf4VY4OtVqd/3c9PmknKQSdbGapbEqlK7mrQPyT0QroMjOkpwpf
rneqoyUxQro7x6ohZQ9PK5/r9l/xYIu7gasWapdx/qmvKx2Ok8zc++ZkykbQFDJO
A4HSx4MkEnsFlja2FmDu2oH1MExAt/NJJgyS/MQYUQKBgQDZ06Cs75GJexG22lFQ
WTXcqnIDLZbL+jLiQ+yfTMaH3VdIBjYQlm/lN8Jr9TXtoWw8JKp9eTBH+8MtnykE
yk37bJaHOYUXbOBAyJUHH489UoQK3Z1TocAU2beKxoGToqvm43z2ObTYWyHO8OxC
6AsxbrtrP8t8m4BiF64OIc9eMQKBgQC24E1JUlFhVUXBiv1KAfgtvU2koE6Tll2S
yuiP70NsSq7R+L3+w26e3gvTI6npTky8RpcXKxO6nWN/LtOJcQFVp5I8O0GNf+EJ
ISIiBUusB0HZ0+SPueI79mRWzBXdqc29R5i/fjtb1IgOOGswbyW3WESRTjSmz6Ji
+GC6eb3ClQKBgFxnGtzhj7JrY5tWx3G3NlMSduUEPNjwnQ9A0yrMbdeKvJDQGbU1
q+fnnHEhhyvz8y8cOrqZYzLWCPjccJEYpLYIXV6ltuC2DfdNX3KzH5da3qqhUjD9
B7eQl/ylsqgHNLbwP71Pw3iYSCI6L28+cikZGSYo3NBSQsbZ1rsl+oqxAoGBAJ7n
VACsCI6cu9oq3WAbSfzkirzLlrtjYreUnHPFIT7Nvg4xJ1ZhlpNwubGjQZa6NK88
XzkAc0oqTDRNCf5ZNSGqU8UGcDV1sqJuKeyJ0XEPdUbDeczxZgVYWWOaPj23uFAK
EE4Eb6uhhv9kQq95RLqFdj8UR2fS73U0AUjHU/3pAoGBAMNKDeb8LPAafupHbqMl
6GtlYVk8hlsUk3uISptq6Pvenuj0j3K8t3GgLuxl0PhX3HhFIipYIAZJgJ7gL7yx
9QlqjxvUVU6RVhMdIN82Jdrjhf6EHCnUCegpRRYV1mV4DoX+aLrFZHP3uxHfxQG1
dS8s/OjWQV/BSg08ipt0aX4v
-----END PRIVATE KEY-----"""
client_email = "imran-179@resolute-planet-457915-t2.iam.gserviceaccount.com"
client_id = "114289623140991408957"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/imran-179@resolute-planet-457915-t2.iam.gserviceaccount.com"
